
package lab08.monitor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Monitor", targetNamespace = "http://monitor.lab08/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Monitor {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "unregisterAutomat", targetNamespace = "http://monitor.lab08/", className = "lab08.monitor.UnregisterAutomat")
    @ResponseWrapper(localName = "unregisterAutomatResponse", targetNamespace = "http://monitor.lab08/", className = "lab08.monitor.UnregisterAutomatResponse")
    @Action(input = "http://monitor.lab08/Monitor/unregisterAutomatRequest", output = "http://monitor.lab08/Monitor/unregisterAutomatResponse")
    public void unregisterAutomat(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateRequest", targetNamespace = "http://monitor.lab08/", className = "lab08.monitor.UpdateRequest")
    @ResponseWrapper(localName = "updateRequestResponse", targetNamespace = "http://monitor.lab08/", className = "lab08.monitor.UpdateRequestResponse")
    @Action(input = "http://monitor.lab08/Monitor/updateRequestRequest", output = "http://monitor.lab08/Monitor/updateRequestResponse")
    public void updateRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFreePort", targetNamespace = "http://monitor.lab08/", className = "lab08.monitor.GetFreePort")
    @ResponseWrapper(localName = "getFreePortResponse", targetNamespace = "http://monitor.lab08/", className = "lab08.monitor.GetFreePortResponse")
    @Action(input = "http://monitor.lab08/Monitor/getFreePortRequest", output = "http://monitor.lab08/Monitor/getFreePortResponse")
    public int getFreePort();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registerAutomat", targetNamespace = "http://monitor.lab08/", className = "lab08.monitor.RegisterAutomat")
    @ResponseWrapper(localName = "registerAutomatResponse", targetNamespace = "http://monitor.lab08/", className = "lab08.monitor.RegisterAutomatResponse")
    @Action(input = "http://monitor.lab08/Monitor/registerAutomatRequest", output = "http://monitor.lab08/Monitor/registerAutomatResponse")
    public void registerAutomat(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
