
package lab08.monitor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MonitorImplService", targetNamespace = "http://monitor.lab08/", wsdlLocation = "http://localhost:8080/WS/Monitor?wsdl")
public class MonitorImplService
    extends Service
{

    private final static URL MONITORIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MONITORIMPLSERVICE_EXCEPTION;
    private final static QName MONITORIMPLSERVICE_QNAME = new QName("http://monitor.lab08/", "MonitorImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/Monitor?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MONITORIMPLSERVICE_WSDL_LOCATION = url;
        MONITORIMPLSERVICE_EXCEPTION = e;
    }

    public MonitorImplService() {
        super(__getWsdlLocation(), MONITORIMPLSERVICE_QNAME);
    }

    public MonitorImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MONITORIMPLSERVICE_QNAME, features);
    }

    public MonitorImplService(URL wsdlLocation) {
        super(wsdlLocation, MONITORIMPLSERVICE_QNAME);
    }

    public MonitorImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MONITORIMPLSERVICE_QNAME, features);
    }

    public MonitorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MonitorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Monitor
     */
    @WebEndpoint(name = "MonitorImplPort")
    public Monitor getMonitorImplPort() {
        return super.getPort(new QName("http://monitor.lab08/", "MonitorImplPort"), Monitor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Monitor
     */
    @WebEndpoint(name = "MonitorImplPort")
    public Monitor getMonitorImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://monitor.lab08/", "MonitorImplPort"), Monitor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MONITORIMPLSERVICE_EXCEPTION!= null) {
            throw MONITORIMPLSERVICE_EXCEPTION;
        }
        return MONITORIMPLSERVICE_WSDL_LOCATION;
    }

}
