/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_company_SortMain */

#ifndef _Included_com_company_SortMain
#define _Included_com_company_SortMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_company_SortMain
 * Method:    sort01
 * Signature: ([Ljava/lang/Double;Ljava/lang/Boolean;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_com_company_SortMain_sort01
  (JNIEnv *, jobject, jobjectArray, jobject);

/*
 * Class:     com_company_SortMain
 * Method:    sort02
 * Signature: ([Ljava/lang/Double;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_com_company_SortMain_sort02
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_company_SortMain
 * Method:    sort03
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_company_SortMain_sort03
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
