
package lab08.automat;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AutomatImplService", targetNamespace = "http://automat.lab08/", wsdlLocation = "http://localhost:8081/WS/Automat?wsdl")
public class AutomatImplService
    extends Service
{

    private final static URL AUTOMATIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTOMATIMPLSERVICE_EXCEPTION;
    private final static QName AUTOMATIMPLSERVICE_QNAME = new QName("http://automat.lab08/", "AutomatImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/WS/Automat?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTOMATIMPLSERVICE_WSDL_LOCATION = url;
        AUTOMATIMPLSERVICE_EXCEPTION = e;
    }

    public AutomatImplService() {
        super(__getWsdlLocation(), AUTOMATIMPLSERVICE_QNAME);
    }

    public AutomatImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTOMATIMPLSERVICE_QNAME, features);
    }

    public AutomatImplService(URL wsdlLocation) {
        super(wsdlLocation, AUTOMATIMPLSERVICE_QNAME);
    }

    public AutomatImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTOMATIMPLSERVICE_QNAME, features);
    }

    public AutomatImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutomatImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Automat
     */
    @WebEndpoint(name = "AutomatImplPort")
    public Automat getAutomatImplPort() {
        return super.getPort(new QName("http://automat.lab08/", "AutomatImplPort"), Automat.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Automat
     */
    @WebEndpoint(name = "AutomatImplPort")
    public Automat getAutomatImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://automat.lab08/", "AutomatImplPort"), Automat.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTOMATIMPLSERVICE_EXCEPTION!= null) {
            throw AUTOMATIMPLSERVICE_EXCEPTION;
        }
        return AUTOMATIMPLSERVICE_WSDL_LOCATION;
    }

}
