
package lab08.automat;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Automat", targetNamespace = "http://automat.lab08/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Automat {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getId", targetNamespace = "http://automat.lab08/", className = "lab08.automat.GetId")
    @ResponseWrapper(localName = "getIdResponse", targetNamespace = "http://automat.lab08/", className = "lab08.automat.GetIdResponse")
    @Action(input = "http://automat.lab08/Automat/getIdRequest", output = "http://automat.lab08/Automat/getIdResponse")
    public int getId();

    /**
     * 
     * @return
     *     returns java.util.List<lab08.automat.Drink>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItems", targetNamespace = "http://automat.lab08/", className = "lab08.automat.GetItems")
    @ResponseWrapper(localName = "getItemsResponse", targetNamespace = "http://automat.lab08/", className = "lab08.automat.GetItemsResponse")
    @Action(input = "http://automat.lab08/Automat/getItemsRequest", output = "http://automat.lab08/Automat/getItemsResponse")
    public List<Drink> getItems();

}
